#pragma once

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
// #define PERMISSIVE_HOLD
// #define PERMISSIVE_HOLD_PER_KEY

// #define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
